version: '2'
services:
  web:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db
    volumes:
      - .:/code
    working_dir: /code
    command: ./entrypoint.sh

  db:
    image: orchardup/mysql
    environment:
      MYSQL_DATABASE: treestories
